<!DOCTYPE html>
<html>
<head>
<title>UPY3 | Términos y Condiciones</title>
<link rel="icon" type="image/png" href="images/ic_launcher.png" />
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz" rel="stylesheet"><!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Responsive web template, Service Logic, UPY, UPY3, Servicios de transporte, transporte, transporte de personal, transporte para
      estudiantes, transporte Venezuela, Caracas, Barquisimeto, Valencia, web design, Android" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<style>
.header{
    background-size: 100%;
    min-height: 150px;
}
#myDiv{
    
    width:auto;
    height:550px;
    overflow-y:auto;
    text-align: justify;
    background-color: rgb(242, 246, 248);
}
</style>
</head>
<body>
<!--header-->
<?php
    include ('navbar.php');
?>
<!--contact-->	
<div class="container">
    <div class="blog">
        <div class="top-blog">
            <h2>Términos y Condiciones de uso</h2>
            <h2>UPY3</h2>
        </div>
        <div id="myDiv">
            <i>Última actualización: 1 de Julio de 2016</i><br><br>
            <h4><strong>1. Relación contractual</strong></h4><br>
            
Las presentes Condiciones de uso (“Condiciones”) regulan el acceso o uso que usted haga, como persona, desde cualquier país del mundo (excluidos los Estados Unidos y sus territorios y posesiones así como China Continental) de aplicaciones, páginas web, contenido, productos y servicios (los “Servicios”) puestos a disposición por LogicService c.a., una compañía anónima constituida en Venezuela, con domicilio social en Carrera 25 entre calles 27 y 28 nro. 27-71, Barquisimeto, Venezuela, inscrita en el Registro Principal (“Upy3”).<br>
<br><strong>LEA ESTAS CONDICIONES DETENIDAMENTE ANTES DE ACCEDER O USAR LOS SERVICIOS.</strong><br><br>
Mediante su acceso y uso de los Servicios usted acuerda vincularse jurídicamente por estas Condiciones, que establecen una relación contractual entre usted y Upy3. Si usted no acepta estas Condiciones, no podrá acceder o usar los Servicios. Estas Condiciones sustituyen expresamente los acuerdos o compromisos previos con usted. Upy3 podrá poner fin de inmediato a estas Condiciones o cualquiera de los Servicios respecto de usted o, en general, dejar de ofrecer o denegar el acceso a los Servicios o cualquier parte de ellos, en cualquier momento y por cualquier motivo.
Se podrán aplicar condiciones suplementarias a determinados Servicios, como políticas para un evento, una actividad o una promoción particular, y dichas condiciones suplementarias se le comunicarán en relación con los Servicios aplicables. Las condiciones suplementarias se establecen además de las Condiciones, y se considerarán una parte de estas, para los fines de los Servicios aplicables. Las condiciones suplementarias prevalecerán sobre las Condiciones en el caso de conflicto con respecto a los Servicios aplicables.
Upy3 podrá modificar las Condiciones relativas a los Servicios cuando lo considere oportuno. Las modificaciones serán efectivas después de la publicación por parte de Upy3 de dichas Condiciones actualizadas en esta ubicación o las políticas modificadas o condiciones suplementarias sobre el Servicio aplicable. Su acceso o uso continuado de los Servicios después de dicha publicación constituye su consentimiento a vincularse por las Condiciones y sus modificaciones.
La recopilación y el uso que hacemos de la información personal en relación con los Servicios es conforme se dispone en la Política de privacidad de Upy3, disponible en https://www.uber.com/legal. Upy3podrá facilitar a un procesador de reclamaciones o a una aseguradora cualquier información necesaria (incluida su información de contacto) si hubiera quejas, disputas o conflictos, que pudieran incluir un accidente, implicándole a usted y a un tercero (incluido el conductor de la compañía de transporte) y dicha información o dichos datos fueran necesarios para resolver la queja, la disputa o el conflicto.
<br><br><h4><strong>2. Los Servicios</strong></h4><br>
Los Servicios constituyen una plataforma de tecnología que permite a los usuarios de aplicaciones móviles de Upy3 o páginas web proporcionadas como parte de los Servicios (cada una, una “Aplicación”) organizar y planear el transporte y/o servicios de logística con terceros proveedores independientes de dichos servicios, incluidos terceros transportistas independientes y terceros proveedores logísticos independientes, conforme a un acuerdo con Upy3 o algunos afiliados de Upy3 (“Terceros proveedores”). A no ser que Upy3 lo acepte mediante un contrato separado por escrito con usted, los Servicios se ponen a disposición solo para su uso personal, no comercial. USTED RECONOCE QUE Upy3 NO PRESTA SERVICIOS DE TRANSPORTE O DE LOGÍSTICA O FUNCIONA COMO UNA EMPRESA DE TRANSPORTES Y QUE DICHOS SERVICIOS DE TRANSPORTE O LOGÍSTICA SE PRESTAN POR TERCEROS CONTRATISTAS INDEPENDIENTES, QUE NO ESTÁN EMPLEADOS POR UBER NI POR NINGUNA DE SUS AFILIADOS.
Licencia.<br>
Sujeto al cumplimiento de estas Condiciones, Upy3 le otorga una licencia limitada, no exclusiva, no sublicenciable, revocable, no transferible para: (i) el acceso y uso de las Aplicaciones en su dispositivo personal solo en relación con su uso de los Servicios; y (ii) el acceso y uso de cualquier contenido, información y material relacionado que pueda ponerse a disposición a través de los Servicios, en cada caso solo para su uso personal, no comercial. Upy3 y sus licenciantes se reservan cualquier derecho que no haya sido expresamente otorgado por el presente.
Restricciones.<br>
Usted no podrá: (i) retirar cualquier nota de derechos de autor, marca registrada u otra nota de propiedad de cualquier parte de los Servicios; (ii) reproducir, modificar, preparar obras derivadas sobre los Servicios, distribuir, licenciar, arrendar, revender, transferir, exhibir públicamente, presentar públicamente, transmitir, retransmitir o explotar de otra forma los Servicios, excepto como se permita expresamente por Upy3; (iii) descompilar, realizar ingeniería inversa o desmontar los Servicios, excepto como se permita por la ley aplicable; (iv) enlazar, reflejar o enmarcar cualquier parte de los Servicios; (v) causar o lanzar cualquier programa o script con el objeto de extraer, indexar, analizar o de otro modo realizar prospección de datos de cualquier parte de los Servicios o sobrecargar o bloquear indebidamente la operación y/o funcionalidad de cualquier aspecto de los Servicios; o (vi) intentar obtener un acceso no autorizado o dañar cualquier aspecto de los Servicios o sus sistemas o redes relacionados.
Prestación de los Servicios.<br>
Usted reconoce que partes de los Servicios podrán ponerse a disposición bajo varias marcas u opciones de pedidos de Upy3 asociadas con el transporte o los servicios logísticos, incluidas las marcas de pedidos de transporte actualmente denominadas “Upy3”, “Upy taxi”, “UpyEmpresa”, “UpyService”, “UpyEstudiante”, “UpyTravel”, y las marcas de pedidos de servicios logísticos actualmente denominadas ““UpyEncomienda”, “UpyPedidos, Asimismo usted reconoce que los Servicios podrán ponerse a disposición bajo dichas marcas u opciones de pedidos por o en relación con: (i) ciertas subsidiarias o afiliados de Upy3; o (ii) Terceros proveedores independientes, incluidos conductores de empresas de red de transportes, titulares del permiso de carta de transporte o titulares de permisos, autorizaciones o licencias de transporte similares.
Servicios y contenido de Terceros.<br>
Los Servicios podrán ponerse a disposición o ser accesible en relación con servicios y contenido de terceros (incluida la publicidad) que Upy3 no controle. Usted reconoce que podrán ser de aplicación diferentes condiciones y políticas de privacidad al uso que haga de dichos servicios y contenido de terceros. Upy3 no respalda dichos servicios y contenido de terceros y en ningún caso Upy3 será responsable de cualquier producto o servicio de dichos terceros proveedores..
Titularidad.<br>
Los Servicios y todos los derechos relativos a estos son y permanecerán de la propiedad de Uber o de sus licenciantes. Ninguna de estas Condiciones ni su uso de los Servicios le transfieren u otorgan ningún derecho: (i) sobre o en relación con los Servicios, excepto en cuanto a la licencia limitada otorgada anteriormente; o bien (ii) a utilizar o mencionar en cualquier modo a los nombres de empresa, logotipos, nombres de producto y servicio, marcas comerciales o marcas de servicio de Upy3 o de sus licenciantes.
<br><br><h4><strong>3. Su uso de los Servicios</strong></h4><br>
<strong>Cuentas de usuario.</strong><br>
Con el fin de usar la mayor parte de los aspectos de los Servicios, usteddebe registrarse y mantener activa una cuenta personal de usuario de los Servicios (“Cuenta”). Para obtener una Cuenta debe tener como mínimo 18 años, o tener la mayoría de edad legal en su jurisdicción (si es distinta a los 18 años). El registro de la cuenta le requiere que comunique a Upy3 determinada información personal, como su nombre, dirección, número de teléfono móvil, así como por lo menos un método de pago válido (bien una tarjeta de crédito o bien un socio de pago aceptado). Usted se compromete a mantener la información en su Cuenta de forma exacta, completa y actualizada. Si no mantiene la información de Cuenta de forma exacta, completa y actualizada, incluso el tener un método de pago inválido o que haya vencido, podrá resultar en su imposibilidad para acceder y utilizar los Servicios o en la resolución por parte de Upy3 de este Condiciones celebrado con usted. Usted es responsable de toda la actividad que ocurre en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contraseña de su Cuenta. A menos que Upy3 permita otra cosa por escrito, usted solo puede poseer una Cuenta.
Requisitos y conducta del usuario.<br>
El Servicio no está disponible para el uso de personas menores de 18 años. Usted no podrá autorizar a terceros a utilizar su Cuenta, asimismo no podrá permitir a personas menores de 18 años que reciban servicios de transporte o logísticos de Terceros proveedores, a menos que aquellos sean acompañados por usted. No podrá ceder o transferir de otro modo su Cuenta a cualquier otra persona o entidad. Usted acuerda cumplir con todas las leyes aplicables al utilizar los Servicios y solo podrá utilizar los Servicios con fines legítimos (p. ej., no para el transporte de materiales ilegales o peligrosos). En el uso de los Servicios, no causará estorbos, molestias, incomodidades o daños a la propiedad, tanto al Tercero proveedor como a cualquier otra parte. En algunos casos, se le podrá requerir que facilite un documento de identidad para el acceso o uso de los Servicios, y usted acepta que se le podrá denegar el acceso o uso de los Servicios si se niega a facilitar el documento de identidad.
Mensajes de texto.<br>
Al crear una Cuenta, usted acepta que los Servicios le puedan enviar mensajes de texto informativos (SMS) como parte de la actividad comercial normal de su uso de los Servicios. Usted podrá solicitar la no recepción de mensajes de texto informativos (SMS) de Upy3 en cualquier momento enviando un correo electrónico acontacto@upy3.comindicando que no desea recibir más dichos mensajes, junto con el número de teléfono del dispositivo móvil que recibe los mensajes. Usted reconoce que solicitar la no recepción de mensajes de texto informativos (SMS) podrá afectar al uso que usted haga de los Servicios.
Códigos promocionales.<br>
Upy3podrá, a su sola discreción, crear códigos promocionales que podrán ser canjeados por crédito de Cuenta u otros elementos o beneficios relacionados con los Servicios y/o los servicios de un Tercero proveedor, con sujeción a cualquier condición adicional que Upy3establezca sobre la base de cada código promocional (“Códigos promocionales”). Usted acuerda que los Códigos promocionales: (i) deben usarse para la audiencia y el propósito deseado, y de manera lícita; (ii) no podrán duplicarse, venderse o transferirse de ninguna manera, o ponerse a disposición del público general (tanto si se publican en un foro público como de otra forma), a menos que sea con el permiso de Upy3; (iii) podrán ser invalidados por Upy3 en cualquier momento por cualquier motivo sin responsabilidad para Upy3; (iv) podrán usarse solo conforme a las condiciones específicas que Upy3 establezca para dicho Código promocional; (v) no son válidos como efectivo; y (vi) podrán caducar antes de que usted los utiliceUpy3se reserva el derecho de retener o deducir el crédito u otros elementos o beneficios obtenidos a través de la utilización de los Códigos promocionales por usted o cualquier otro usuario en el caso de que Upy3 determine o crea que el uso o el canje de los Códigos promocionales fue de modo erróneo, fraudulento, ilegal o infringiendo las condiciones del Código promocional o las presentes Condiciones.
Contenido proporcionado por el Usuario.<br>
Upy3podrá, a su sola discreción, permitirle cuando considere oportuno, que envíe, cargue, publique o de otro modo ponga a disposición deUpy3a través de los Servicios contenido e información de texto, audio y/o visual, incluidos comentarios y opiniones relativos a los Servicios, iniciación de peticiones de apoyo, así como presentación de admisiones para competiciones y promociones (“Contenido de usuario”). Todo Contenido de usuario facilitado por usted seguirá siendo de su propiedad. No obstante, al proporcionar Contenido de usuario a Upy3, usted otorga una licencia mundial, perpetua, irrevocable, transferible, libre de regalías, con derecho a sublicenciar, usar, copiar, modificar, crear obras derivadas, distribuir, exhibir públicamente, presentar públicamente o de otro modo explotar de cualquier manera dicho Contenido de usuario en todos los formatos y canales de distribución, conocidos ahora o ideados en un futuro (incluidos en relación con los Servicios y el negocio de Upy3 y en sitios y servicios de terceros), sin más aviso o consentimiento de usted y sin requerirse el pago a usted o a cualquier otra persona o entidad.<br>
Usted declara y garantiza que: (i) es el único y exclusivo propietario de todo el Contenido de usuario o que tiene todos los derechos, licencias, consentimientos y permisos necesarios para otorgar aUpy3la licencia al Contenido de usuario como establecido anteriormente; y (ii) ni el Contenido de usuario ni su presentación, carga, publicación o puesta a disposición de otro modo de dicho Contenido de usuario, ni el uso por parte de Upy3del Contenido de usuario como está aquí permitido, infringirán, malversarán o violarán la propiedad intelectual o los derechos de propiedad de un tercero o los derechos de publicidad o privacidad o resultarán en la violación de cualquier ley o reglamento aplicable.<br>
Usted acuerda no proporcionar Contenido de usuario que sea difamatorio, calumnioso, odioso, violento, obsceno, pornográfico, ilícito o de otro modo ofensivo, como determine Upy3, a su sola discreción, tanto si dicho material pueda estar protegido o no por la ley. Upy3podrá, a su sola discreción y en cualquier momento y por cualquier motivo, sin avisarle previamente, revisar, controlar o eliminar Contenido de usuario, pero sin estar obligada a ello.<br>
<br><strong>Acceso a la red y dispositivos.</strong><br>
Usted es responsable de obtener el acceso a la red de datos necesario para utilizar los Servicios. Podrán aplicarse las tarifas y tasas de datos y mensajes de su red móvil si usted accede o utiliza los Servicios desde un dispositivo inalámbrico y usted será responsable de dichas tarifas y tasas. Usted es responsable de adquirir y actualizar el hardware compatible o los dispositivos necesarios para acceder y utilizar los Servicios y Aplicaciones y cualquier actualización de estos. Upy3no garantiza que los Servicios, o cualquier parte de estos, funcionen en cualquier hardware o dispositivo particular. Además, los Servicios podrán ser objeto de disfunciones o retrasos inherentes al uso de Internet y de las comunicaciones electrónicas.
<br><br><h4><strong>4. Pago</strong></h4><br>
Usted entiende que el uso de los Servicios puede derivar en cargos por los servicios o bienes que reciba de un Tercer proveedor (“Cargos”). Después de que haya recibido los servicios u obtenido los bienes mediante el uso de los Servicios, Upy3 facilitará su pago de los Cargos aplicables en nombre del Tercero proveedor como agente de cobro limitado del Tercero proveedor. El pago de los Cargos de dicha manera se considerará como el pago efectuado directamente por usted al Tercero proveedor. Los Cargos incluirán los impuestos aplicables cuando se requiera por ley. Los Cargos pagados por usted son definitivos y no reembolsables, a menos que Upy3 determine lo contrario. Usted conserva el derecho de solicitar Cargos más bajos de un Tercero proveedor para los servicios o bienes recibidos por usted de dicho Tercero proveedor en el momento en que reciba dichos servicios o bienes. Upy3responderá en consecuencia a cualquier solicitud de un Tercero proveedor para modificar los Cargos por un servicio o bien en particular.<br>
Todos los Cargos son pagaderos inmediatamente y el pago se facilitará por Upy3 utilizando al método de pago preferido indicado en su Cuenta, y después de ello Upy3 le enviará un recibo por correo electrónico. Si se determina que el método de pago de su Cuenta principal ha caducado, es inválido o de otro modo no sirve para cobrarle, usted acepta que Uber, como agente de cobro limitado del Tercero proveedor, utilice un método de pago secundario en su Cuenta, si estuviera disponible.<br>
Upy3r, en cualquier momento y a su sola discreción, se reserva el derecho de establecer, eliminar y/o revisar los Cargos para alguno o todos los servicios o bienes obtenidos a través del uso de los Servicios. Además, usted reconoce y acepta que los Cargos aplicables en determinadas zonas geográficas podrán incrementar sustancialmente durante los periodos de alta demanda. Upy3 usará los esfuerzos razonables para informarle de los Cargos que podrán aplicarse, siempre y cuando usted sea responsable de los Cargos incurridos en su Cuenta, independientemente de que usted conozca dichos Cargos o los importes de estos. Uber podrá, cuando lo considere oportuno, proporcionar a determinados usuarios ofertas promocionales y descuentos que pueden resultar en el cobro de diferentes importes por estos o similares servicios o bienes obtenidos a través del uso de los Servicios, y usted acepta que dichas ofertas promocionales y descuentos, a menos que también se pongan a su disposición, no se tendrán en cuenta en el uso por su parte de los Servicios o los Cargos aplicados a usted. Usted podrá optar por cancelar su solicitud para los servicios o bienes de un Tercero proveedor en cualquier momento antes de la llegada de ese Tercero proveedor, en cuyo caso se le podrá cobrar una tasa de cancelación.<br>
Esta estructura de pago está destinada para compensar plenamente al Tercero proveedor por los servicios o bienes proporcionados. Excepto con respecto a los servicios de transporte envehiculos solicitados mediante la Aplicación, Upy3 no designa ninguna parte de su pago como propina o gratificación al Tercero proveedor. Cualquier manifestación por parte de Upy3 (en la página web de Upy3 o en los materiales de marketing de Upy3) en el sentido de que dar una propina es “voluntario”, “no requerido”, y/o “incluido” en los pagos que realiza para los servicios o bienes proporcionados no pretende sugerir que Upy3 proporciona importes adicionales, aparte de los descritos anteriormente, al Tercero proveedor. Usted entiende y acepta que, mientras es libre de proporcionar un pago adicional como gratificación a cualquier Tercero proveedor que le proporcione servicios o bienes obtenidos mediante el Servicios, no tiene obligación de ello. Las gratificaciones son voluntarias. Después de que haya recibido los bienes o servicios obtenidos a través del Servicio, tendrá la oportunidad de calificar su experiencia y dejar comentarios adicionales sobre el Tercero proveedor.<br>
<br><strong>Tarifa de reparación o limpieza.</strong><br>
Usted será responsable del coste de la reparación por daños o de la limpieza necesaria de los vehículos y las propiedades del Tercero proveedor, que se ocasionen por el uso de los Servicios en su Cuenta que sobrepasen los daños considerados normales por “el desgaste” y la limpieza necesaria (“Reparación o Limpieza”). En el caso de que un Tercero proveedor informe de la necesidad de reparación o limpieza, y dicha reparación o limpieza se verifique por Upy3 a su razonable discreción, Upy3se reserva el derecho de facilitar el pago por el coste razonable de dicha reparación o limpieza en nombre del Tercero proveedor utilizando su método de pago indicado en su Cuenta. Dichos importes se transferirán por Upy3 al correspondiente Tercero proveedor y no son reembolsables.<br>
<br><h4><strong>5. Renuncias; Limitación de responsabilidad; Indemnidad.</strong></h4><br>
<strong>RENUNCIA.</strong><br>
LOS SERVICIOS SE PROPORCIONAN “TAL CUAL” Y “COMO DISPONIBLES”. UBER RENUNCIA A TODA DECLARACIÓN Y GARANTÍA, EXPRESA, IMPLÍCITA O ESTATUTARIA, NO EXPRESAMENTE ESTABLECIDA EN ESTAS CONDICIONES, INCLUIDAS LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN PARTICULAR Y NO VIOLACIÓN. ADEMÁS, UBER NO HACE DECLARACIÓN NI PRESTA GARANTÍA ALGUNA RELATIVA A LA FIABILIDAD, PUNTUALIDAD, CALIDAD, IDONEIDAD O DISPONIBILIDAD DE LOS SERVICIOS O CUALQUIERA DE LOS SERVICIOS O BIENES SOLICITADOS A TRAVÉS DEL USO DE LOS SERVICIOS, O QUE LOS SERVICIOS NO SERÁN INTERRUMPIDOS O ESTARÁN LIBRES DE ERRORES. UBER NO GARANTIZA LA CALIDAD, IDONEIDAD, SEGURIDAD O HABILIDAD DE LOS TERCEROS PROVEEDORES. USTED ACUERDA QUE TODO RIESGO DERIVADO DE SU USO DE LOS SERVICIOS Y CUALQUIER SERVICIO O BIEN SOLICITADO EN RELACIÓN CON AQUELLOS SERÁ ÚNICAMENTE SUYO, EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY APLICABLE.<br>
<br><strong>LIMITACIÓN DE RESPONSABILIDAD.</strong><br>
UBER NO SERÁ RESPONSABLE DE DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, EJEMPLARES, PUNITIVOS O EMERGENTES, INCLUIDOS EL LUCRO CESANTE, LA PÉRDIDA DE DATOS, LA LESIÓN PERSONAL O EL DAÑO A LA PROPIEDAD, NI DE PERJUICIOS RELATIVOS, O EN RELACIÓN CON, O DE OTRO MODO DERIVADOS DE CUALQUIER USO DE LOS SERVICIOS, INCLUSO AUNQUE UBER HAYA SIDO ADVERTIDO DE LA POSIBILIDAD DE DICHOS DAÑOS. UBER NO SERÁ RESPONSABLE DE CUALQUIER DAÑO, RESPONSABILIDAD O PÉRDIDA QUE DERIVEN DE: (I) SU USO O DEPENDENCIA DE LOS SERVICIOS O SU INCAPACIDAD PARA ACCEDER O UTILIZAR LOS SERVICIOS; O (ii) CUALQUIER TRANSACCIÓN O RELACIÓN ENTRE USTED Y CUALQUIER TERCERO PROVEEDOR, AUNQUE UBER HUBIERA SIDO ADVERTIDO DE LA POSIBILIDAD DE DICHOS DAÑOS. UBER NO SERÁ RESPONSABLE DEL RETRASO O DE LA FALTA DE EJECUCIÓN RESULTANTE DE CAUSAS QUE VAYAN MÁS ALLÁ DEL CONTROL RAZONABLE DE UBER. USTED RECONOCE QUE LOS TERCEROS PROVEEDORES DE TRANSPORTE QUE PRESTEN SERVICIOS DE TRANSPORTE SOLICITADOS A TRAVÉS DE ALGUNAS MARCAS DE PEDIDOS PODRÁN OFRECER SERVICIOS DE COCHE COMPARTIDO O ENTRE PARES (PEER-TO-PEER) Y PUEDE QUE NO DISPONGAN DE LA LICENCIA O DEL PERMISO PROFESIONAL. EN NINGÚN CASO LA RESPONSABILIDAD TOTAL DE Upy3 HACIA USTED EN RELACIÓN CON LOS SERVICIOS POR TODOS LOS DAÑOS, LAS PÉRDIDAS Y LOS JUICIOS PODRÁ EXCEDER DE QUINIENTOS EUROS ($500).<br>
USTED PODRÁ UTILIZAR LOS SERVICIOS DE UBER PARA SOLICITAR Y PLANIFICAR SERVICIOS DE TRANSPORTE, BIENES O LOGÍSTICOS CON TERCEROS PROVEEDORES, PERO ACEPTA QUE UBER NO TIENE RESPONSABILIDAD ALGUNA HACIA USTED EN RELACIÓN CON CUALQUIER SERVICIO DE TRANSPORTE, BIENES O LOGÍSTICO PRESTADO A USTED POR TERCEROS PROVEEDORES QUE NO SEA COMO SE HA ESTABLECIDO EXPRESAMENTE EN ESTAS CONDICIONES.<br>
LAS LIMITACIONES Y LA RENUNCIA EN ESTE APARTADO 5 NO PRETENDEN LIMITAR LA RESPONSABILIDAD O ALTERAR SUS DERECHOS COMO CONSUMIDOR QUE NO PUEDAN EXCLUIRSE SEGÚN LA LEY APLICABLE.<br>
<br><strong>Indemnidad.</strong><br>
Usted acuerda mantener indemnes y responder frente a Uber y sus consejeros, directores, empleados y agentes por cualquier reclamación, demanda, pérdida, responsabilidad y gasto (incluidos los honorarios de abogados) que deriven de: (i) su uso de los Servicios o servicios o bienes obtenidos a través de su uso de los Servicios; (ii) su incumplimiento o violación de cualquiera de estas Condiciones; (iii) el uso por parte de Uber de su Contenido de usuario; o (iv) su infracción de los derechos de cualquier tercero, incluidos Terceros proveedores.<br>
<br><h4><strong>6. Legislación aplicable; Arbitraje.</strong></h4><br>
Salvo que aquí se especifique lo contrario, las presentes Condiciones se regirán e interpretarán exclusivamente en virtud de la legislación de la República Bolivariana de Venezuela. Cualquier disputa, conflicto, reclamación o controversia, del tipo que sea, que resulte de las presentes Condiciones o que se relacione en gran parte con ellas, incluyendo las relativas a su validez, interpretación y exigibilidad (cualquier “Disputa”), deberán someterse forzosamente a procedimientos de mediación en virtud. La existencia y el contenido de los procedimientos de mediación y arbitraje, incluidos los documentos e informes presentados por las partes, la correspondencia del mediador y la correspondencia, los pedidos y los laudos emitidos por el único árbitro deberán permanecer en estricta confidencialidad y no deberán ser revelados a ningún tercero sin el consentimiento expreso por escrito de la otra parte, a menos que: (i) la revelación al tercero sea razonablemente necesaria para llevar a cabo el procedimiento de mediación o arbitraje; y (ii) el tercero acepte incondicionalmente por escrito estar sujeto a la obligación de confidencialidad estipulada en el presente documento.<br>
<br><h4><strong>7. Otras disposiciones</strong></h4><br>
<strong>Reclamaciones por infracción de derechos de autor.</strong><br>
Las reclamaciones por infracción de derechos de autor deberán enviarse al agente designado de Upy3. Visite la página web de Upy3 en https://www.upy3.com/legalpara obtener las direcciones designadas e información adicional.<br>
<br><strong>Notificaciones.</strong><br>
Upy3podrá notificar por medio de una notificación general en los Servicios, mediante un correo electrónico enviado a su dirección electrónica en su Cuenta o por comunicación escrita enviada a su dirección, según lo dispuesto en su Cuenta. Usted podrá notificar a Upy3 por comunicación escrita a la dirección de Upy3en Venezuela.<br>
<br><h4><strong>Disposiciones generales.</strong></h4><br>
No podrá ceder ni transferir estas Condiciones, en todo o en parte, sin el consentimiento previo por escrito de Upy3. Usted da su aprobación a Upy3 para ceder o transferir estas Condiciones, en todo o en parte, incluido a: (i) una subsidiaria o un afiliado; (ii) un adquirente del capital, del negocio o de los activos de Upy3; o (iii) un sucesor por fusión. No existe entre usted, Upy3 o cualquier Tercer proveedor una empresa conjunta o relación de socios, empleo o agencia como resultado del contrato entre usted yUpy3o del uso de los Servicios.<br>
Si cualquier disposición de estas Condiciones se considerara ilegal, nula o inexigible, ya sea en su totalidad o en parte, de conformidad con cualquier legislación, dicha disposición o parte de esta se considerará que no forma parte de estas Condiciones, aunque la legalidad, validez y exigibilidad del resto de las disposiciones de estas Condiciones no se verá afectada. En ese caso, las partes deberán reemplazar dicha disposición ilegal, nula o inexigible, en todo o en parte por una disposición legal, válida y exigible que tenga, en la medida de lo posible, un efecto similar al que tenía la disposición ilegal, nula o inexigible, dados los contenidos y el propósito de estas Condiciones. Estas Condiciones constituyen el contrato íntegro y el entendimiento entre las partes en relación con el objeto y sustituye y reemplaza a todos los contratos o acuerdos anteriores o contemporáneos en relación con dicho objeto. En estas Condiciones, las palabras “incluido/a/os/as” e “incluye/n” significan “incluido, de forma meramente enunciativa”.<br>

        <div class="clearfix"></div>
	</div>
    </div>
</div>

    <?php
        include('address.php');
        include('footer.php');
    ?>
</body>
</html>